<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public  function getLastComments($nb=5){
        $query = $this->createQueryBuilder('comment')
            ->join('comment.author','user')
            ->addSelect('user')
            ->join('AppBundle:Serie','serie')
            ->where('comment.thread = serie.id')
            ->getQuery();

        return $query->getResult();
    }
}
