<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends EntityRepository
{
	 public function getAll(){
        $query = $this->createQueryBuilder('episode')
            ->select('episode')
            ->orderBy('episode.name','ASC')
            ->where('episode.validated=:is_validated')
            ->setParameter(':is_validated',false)
            ->getQuery();
          

        return $query->getResult();
    }
}
