<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends EntityRepository
{
    public function countNotValidated(){
        $query = $this->createQueryBuilder('episode')
            ->select('COUNT(episode)')
            ->where('episode.validated = false')
            ->getQuery();

        return $query->getSingleScalarResult();
    }
}
