<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends EntityRepository
{
    public function countNotValidated(){
        $query = $this->createQueryBuilder('serie')
            ->select('COUNT(serie)')
            ->where('serie.validated = false')
            ->getQuery();

        return $query->getSingleScalarResult();
    }
}
