<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TchatRepository extends EntityRepository
{
    public function getLast($nb = 10){
        $query = $this->createQueryBuilder('tchat')
            ->select('tchat')
            ->orderBy('tchat.date', 'DESC')
            ->setMaxResults($nb)
            ->getQuery();

        return $query->getResult();
    }
}
