<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    public function countVotesByUser($userId){
        $query = $this->createQueryBuilder('v')
            ->select('COUNT(v)')
            ->where('v.voter = :userId')
            ->setParameter(':userId', $userId)
            ->getQuery();
        return $query->getSingleScalarResult();
    }
}
