# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    #app.comments.vote_persistence_listener.class: AppBundle\EventListener\CommentVotePersistenceListener

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.validator:
        class: AppBundle\Utils\NotValidated
        arguments: [@doctrine.orm.entity_manager]
    app.get.this:
            class: AppBundle\Utils\WhatIsThis
            arguments: [@doctrine.orm.entity_manager]
    app.form.registration:
            class: AppBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }
    app.form.profile:
                class: AppBundle\Form\ProfileType
                tags:
                    - { name: form.type, alias: app_user_profile }
    #acme.comments.vote_persistence_listener:
       # class: %app.comments.vote_persistence_listener.class%
        #arguments: [ @fos_comment.manager.vote.default, @security.context ]
        #tags:
            #- { name: kernel.event_subscriber }

